# Generated by Django 3.2.16 on 2022-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_choice', '0002_auto_20221119_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='multi_choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
